name: Install Kubeflow with Cognito using terraform
on:
  pull_request:
    paths:
      - deployments/cognito/terraform/**
      - iaac/terraform/aws-infra/cognito/**
jobs:
  build:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.PR_BUILD_ROLE }}
        role-session-name: prrolesession
        aws-region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Plan and apply terraform
      env:
        TF_VAR_cognito_user_pool_name: testpool-${{ github.run_id }}-${{ github.run_attempt }}
        TF_VAR_aws_route53_zone_id: ${{ secrets.HOSTED_ZONE_ID }}
      run: |
        cd iaac/terraform/aws-infra/cognito
        terraform init
        terraform plan
        terraform apply -auto-approve
        terraform state list
    - name: Clean up
      if: success() || failure()
      run: |
        cd iaac/terraform/aws-infra/cognito
        terraform destroy -auto-approve